version: '3.8'

services:
  drupal:
    image: docker.io/osuwams/drupal:8-apache-dev
    environment:
      - DRUPAL_DBHOST=database
      - DRUPAL_DBUSER=drupal
      - DRUPAL_DBPASS=drupal
      - DRUPAL_DBNAME=drupal
      - DRUPAL_MEMCACHEHOST=cache
      - DRUPAL_THEME_DEVEL=true
    ports:
      - 8080:80
    volumes:
      - drupal-files:/var/www/html/docroot/sites/default/files
      - ./:/var/www/html/docroot/themes/custom/madrone:Z
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    restart: unless-stopped
  database:
    image: docker.io/library/mariadb:10.7
    volumes:
      - drupal-db:/var/lib/mysql/drupal
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: unless-stopped
  cache:
    image: docker.io/library/memcached:latest
    networks:
      - internal
    restart: unless-stopped

volumes:
  drupal-db:
  drupal-files:
